services:
  backend:
    build: ./backend
    container_name: django_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    dns:
      - 8.8.8.8   # Google's public DNS
      - 1.1.1.1   # Cloudflare's DNS

  nginx:
    build: ./nginx      # Points to Dockerfile in ./nginx/
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend

volumes:
  mongo_data:
